global using ApplicationLayerProject.Aggregates;
global using ApplicationLayerProject.DTOs.CreateOrder;
global using ApplicationLayerProject.Ports.UseCases.CreateOrder;
global using ApplicationLayerProject.UseCases_Interfaces_.Repositories;
